import Head from 'next/head'
import Image from 'next/image'

import Header from '../components/Header'
import Hero from '../components/Hero'
import Welcome from '../components/Welcome'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import About from '../components/About'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-48">
        <Header />

        <Hero />

        <Welcome />

        <Projects />

        <Skills />

        <About />

      </main>
      <Footer />
 
    </div>
  )
}
